pipeline:
  build:
    image: ntradingplus
    commands:
      - export PATH=$PATH:/root/Nim/bin/
      - nim cpp --cincludes:. -r core/ffi/cccobject.nim
  
  telegram:
    image: appleboy/drone-telegram
    token: 527210046:AAGlH4SFuOAnLAv9h9Eq9FYhXvhygU_tSxo
    to: -1001299936375
    message: >
      {{#success build.status}}
        👍 Build {{build.number}} of {{repo.name}} @ {{commit.branch}}
        {{commit.message}} by {{commit.author}} succeeded. Good job.
        {{build.link}}
      {{else}}
        🚫 Build {{build.number}} of {{repo.name}} @ {{commit.branch}}
        {{commit.message}} by {{commit.author}} failed. Fix me please.
        {{build.link}}
      {{/success}}
    when:
      status: [ success, failure ]
