variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
test_ffi_cpp_linux:
  script:
    - nim cpp --cincludes:. -r core/ffi/cpp.nim
  tags:
    - NIM, LINUX
    
test_ffi_cpp_win_gcc:
  script:
    - nim cpp --cincludes:. -r core/ffi/cpp.nim
  tags:
    - NIM, WIN10
    
test_ffi_cpp_win_vcc:
  script:
    - nim cpp --cc:vcc --cincludes:. -r core/ffi/cpp.nim
  tags:
    - NIM, WIN10